"""
Full-population read-back: intent equals what the database holds
================================================================
P0-A-1. The publication prerequisite:

    for every canonical row in the intended serving population, the canonical
    payload generated by the run equals the canonical payload read back from
    PostgreSQL.

The check it replaces read 25 codes — 1.2% of the serving population. A spot
check, whatever it was called, and it could not answer the question
publication depends on: did the write land, in full, for everyone.

These tests use the REAL governed metric set and the REAL contract, against a
fake cursor. Constructing a 72-metric row by hand would test a toy; generating
it from ``governed_for()`` means a metric added to the model appears here
automatically, and a renamed column breaks the test rather than sliding past
it.

The cases correspond to the four ways publication can be wrong, which fail
differently and must be reported differently:

    population    intended, written and attributable are the same set
    attribution   every row carries THIS run id
    contract      states and causes are internally coherent
    equality      normalised intent payload == normalised read-back payload

Plus the one that motivated the whole design: a value the run did not write,
which survived from run N-1, is indistinguishable in the final row from one
the run wrote — unless the row is compared against what the run intended.

Run under pytest, or standalone:
    cd /opt/asx-screener/backend && ../asx-venv/bin/python tests/test_canonical_readback.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from compute.engine.applicability import (  # noqa: E402
    Applicability, Assessment, Cause, Domain, UNSUPPORTED_COMPUTATION,
)
from compute.engine.canonical_readback import (  # noqa: E402
    ReadBackReport, column_scales, payload_hash, quantise, row_payload,
    verify_population,
)
from compute.engine.metric_states import LATEST_MODEL_VERSION  # noqa: E402
from compute.engine.universe_writer import (  # noqa: E402
    ComputeRun, column_for, governed_for, normalise,
)

VERSION = LATEST_MODEL_VERSION
METRICS = sorted(governed_for(VERSION))
COLUMNS = [column_for(m) for m in METRICS]


class Run:
    """Minimal stand-in: verify_population reads only these two fields."""
    run_id = 42
    factor_model_version = VERSION


def _assessment(metric: str, value):
    """An APPLICABLE assessment, or the unsupported one where the contract
    demands it — piotroski_f_score may never carry a value."""
    if normalise(metric) in UNSUPPORTED_COMPUTATION:
        return Assessment(metric, Applicability.UNAVAILABLE, None,
                          UNSUPPORTED_COMPUTATION[normalise(metric)],
                          Domain.GENERAL_CORPORATE,
                          cause=Cause.COMPUTATION_UNSUPPORTED)
    return Assessment(metric, Applicability.APPLICABLE, value, "",
                      Domain.GENERAL_CORPORATE)


def _intent(codes, value=0.25):
    return {c: {m: _assessment(m, value) for m in METRICS} for c in codes}


def _stored_row(code, value=0.25, override=None):
    """What the bulk SELECT returns: (code, *values, metric_states)."""
    states = {}
    values = []
    for m in METRICS:
        if normalise(m) in UNSUPPORTED_COMPUTATION:
            values.append(None)
            states[m] = {"state": "unavailable",
                         "cause": "computation_unsupported",
                         "reason": UNSUPPORTED_COMPUTATION[normalise(m)]}
        elif override and m in override:
            values.append(override[m])
        else:
            values.append(value)
    return (code, *values, states)


class FakeCur:
    """Answers the two queries verify_population issues, and nothing else."""

    def __init__(self, rows, scale=6):
        self.rows, self.scale, self._result = rows, scale, []

    def execute(self, sql, params=None):
        if "information_schema" in sql:
            self._result = [(c, self.scale) for c in COLUMNS]
        elif "compute_run_id" in sql:
            assert params == (Run.run_id,), "the read-back must be run-scoped"
            self._result = self.rows
        else:
            raise AssertionError(f"unexpected query: {sql[:80]}")

    def fetchall(self):
        return self._result


# ── The happy path, and the precision hazard it hides ────────────────────────

def test_identical_intent_and_storage_verifies():
    codes = ["AAA", "BBB", "CCC"]
    report = verify_population(FakeCur([_stored_row(c) for c in codes]),
                               _intent(codes), Run(), rows_written=3)

    assert report.ok, report.summary()
    assert report.read_back == 3 and report.intended == 3


def test_full_precision_intent_does_not_fail_against_a_quantised_column():
    """The hazard that would have made this validator unusable.

    storage_value does not round; PostgreSQL rounds to the column scale on
    INSERT. Intent 0.123456789 becomes stored 0.123457, and a naive comparison
    reports every row as a mismatch — a validator that blocks publication
    permanently, for something that is not a defect.
    """
    codes = ["AAA"]
    intent = _intent(codes, value=0.1234567891)
    stored = [_stored_row("AAA", value=0.123457)]

    report = verify_population(FakeCur(stored), intent, Run(), rows_written=1)

    assert report.ok, f"precision reconciliation failed: {report.summary()}"


def test_ties_round_away_from_zero_as_postgresql_does():
    """Decimal.quantize() defaults to ROUND_HALF_EVEN; PostgreSQL NUMERIC
    rounds half away from zero. They agree everywhere except exact ties, and
    on ties they differ whenever the preceding digit is even.

    Confirmed against the database by scripts/p0a_quantise_probe.py:
    ROUND_HALF_UP matches, ROUND_HALF_EVEN does not. No fixture here can
    establish that — which is why the probe exists — but this holds the
    conclusion in place.
    """
    assert quantise(0.1234565, 6) == "0.123457"   # HALF_EVEN would give ...456
    assert quantise(0.12345, 4) == "0.1235"       # HALF_EVEN would give 0.1234
    assert quantise(-0.1234565, 6) == "-0.123457"  # away from zero, not toward
    assert quantise(-1.5, 0) == "-2"


def test_negative_zero_is_not_a_different_number():
    """The probe's second finding, on eight of eight persisted types.

    Decimal preserves the sign through rounding, so -0.0049 at scale 2 is
    Decimal('-0.00'); PostgreSQL normalises the sign away and returns 0.00.
    Comparing the strings would report a payload mismatch for any metric whose
    intent is a small negative that rounds to zero — a near-flat negative
    return, a marginally negative margin — and publication would be blocked by
    the validator's own arithmetic.
    """
    from decimal import Decimal as D

    for value, scale in ((-0.0049, 2), (-4.9e-07, 6), (-0.49, 0), (-4.9e-05, 4)):
        intent = quantise(value, scale)
        assert not intent.startswith("-"), (
            f"quantise({value!r}, {scale}) kept a negative zero: {intent}")
        # And it must equal what the database side normalises to, whether
        # psycopg2 hands back Decimal or float.
        assert intent == quantise(D(0).quantize(D(1).scaleb(-scale)), scale)
        assert intent == quantise(0.0, scale)

    # A genuine negative must keep its sign.
    assert quantise(-0.25, 2) == "-0.25"


def test_a_real_difference_is_still_caught():
    """Quantisation must reconcile precision, not substance."""
    codes = ["AAA"]
    report = verify_population(FakeCur([_stored_row("AAA", value=0.9)]),
                               _intent(codes, value=0.25), Run(), rows_written=1)

    assert not report.ok
    assert report.mismatched, "a materially different value was not reported"
    assert report.hash_differs == ["AAA"]


# ── Population ───────────────────────────────────────────────────────────────

def test_an_intended_row_that_never_landed_is_reported():
    codes = ["AAA", "BBB"]
    report = verify_population(FakeCur([_stored_row("AAA")]),
                               _intent(codes), Run(), rows_written=2)

    assert not report.ok
    assert report.missing == ["BBB"]


def test_a_row_attributed_to_this_run_but_never_intended_is_reported():
    """The inverse, and equally a defect: something claimed this run's
    attribution that this run did not produce."""
    report = verify_population(
        FakeCur([_stored_row("AAA"), _stored_row("ZZZ")]),
        _intent(["AAA"]), Run(), rows_written=1)

    assert not report.ok
    assert report.unexpected == ["ZZZ"]


def test_the_read_back_is_scoped_to_this_run():
    """Asserted inside FakeCur.execute. Reading the current row and hoping it
    came from this write is the timestamp-matching fallacy in another costume."""
    verify_population(FakeCur([_stored_row("AAA")]), _intent(["AAA"]),
                      Run(), rows_written=1)


# ── The property the whole design exists for ─────────────────────────────────

def test_a_stale_prior_run_value_cannot_survive_silently():
    """Run N intends to withhold a metric. Run N-1's value is still in the
    column because run N's write omitted it.

    In the final row this is indistinguishable from a value run N wrote —
    which is exactly why the comparison is against intent, not against
    plausibility. No pre-state fingerprint is required: a surviving N-1 value
    IS a payload difference.
    """
    codes = ["AAA"]
    intent = _intent(codes)
    # Run N decides roe is not meaningful for this company: NULL, with a state.
    intent["AAA"]["roe"] = Assessment(
        "roe", Applicability.NOT_MEANINGFUL, None,
        "negative or zero equity inverts the ratio's meaning",
        Domain.GENERAL_CORPORATE, cause=Cause.OBSERVATION)

    # But the column still holds run N-1's number.
    stored = [_stored_row("AAA", override={"roe": 0.25})]

    report = verify_population(FakeCur(stored), intent, Run(), rows_written=1)

    assert not report.ok, "a surviving prior-run value was not detected"
    offenders = {m for _, m, _, _ in report.mismatched}
    assert "roe" in offenders, f"roe not named among {offenders}"
    assert report.hash_differs == ["AAA"]


# ── Diagnosability ───────────────────────────────────────────────────────────

def test_a_failure_names_the_row_the_metric_and_both_values():
    """A hash-only validator that says "hashes differ" sends you back for
    another 25-minute run to learn what it already knew."""
    report = verify_population(
        FakeCur([_stored_row("AAA", override={"roe": 0.9})]),
        _intent(["AAA"]), Run(), rows_written=1)

    assert report.mismatched
    code, metric, want, got = report.mismatched[0]
    assert code == "AAA" and metric == "roe"
    assert want != got and want is not None and got is not None


def test_the_report_distinguishes_its_failure_kinds():
    """Population, attribution, contract and equality failures have different
    causes and different responses; a single count would collapse them."""
    r = ReadBackReport(intended=2, written=2, read_back=1)
    r.missing = ["BBB"]
    assert not r.ok and r.failure_count == 1
    assert "absent" in r.summary()

    r2 = ReadBackReport(intended=1, written=1, read_back=1)
    r2.mismatched = [("AAA", "roe", "0.1", "0.2")]
    assert "field mismatches" in r2.summary()


def test_scales_are_read_from_the_database_not_assumed():
    """A single rounding constant would be right for NUMERIC(10,6) and
    silently wrong for NUMERIC(12,4), SMALLINT and BOOLEAN."""
    cur = FakeCur([], scale=4)
    scales = column_scales(cur, COLUMNS)

    assert set(scales) == set(COLUMNS)
    assert all(v == 4 for v in scales.values())

    # A column the contract needs but the table lacks must abort, not default.
    class Short(FakeCur):
        def execute(self, sql, params=None):
            self._result = [(c, 6) for c in COLUMNS[:-1]]
    try:
        column_scales(Short([]), COLUMNS)
    except RuntimeError as e:
        assert "missing columns" in str(e)
    else:
        raise AssertionError("a missing column must abort the read-back")


if __name__ == "__main__":
    tests = [(n, f) for n, f in sorted(globals().items())
             if n.startswith("test_") and callable(f)]
    failures = []
    for name, fn in tests:
        try:
            fn()
            print(f"  PASS  {name}")
        except AssertionError as e:
            failures.append(name)
            print(f"  FAIL  {name}  - {e}")
        except Exception as e:
            failures.append(name)
            print(f"  ERROR {name}  - {type(e).__name__}: {e}")

    print(f"\n{len(tests) - len(failures)}/{len(tests)} passed")
    sys.exit(1 if failures else 0)
