-- Widen narrow NUMERIC(8,4) ratio/percentage columns to DOUBLE PRECISION.
-- Blocked by views screener.fundamentals + screener.technicals, so we drop and
-- recreate them around the ALTER. Wrapped in a transaction (atomic).

BEGIN;

DROP VIEW IF EXISTS screener.fundamentals;
DROP VIEW IF EXISTS screener.technicals;

ALTER TABLE screener.universe
    ALTER COLUMN adx_14                   TYPE DOUBLE PRECISION,
    ALTER COLUMN altman_z_score           TYPE DOUBLE PRECISION,
    ALTER COLUMN analyst_upside           TYPE DOUBLE PRECISION,
    ALTER COLUMN avg_roe_3y               TYPE DOUBLE PRECISION,
    ALTER COLUMN bb_pct                   TYPE DOUBLE PRECISION,
    ALTER COLUMN beta_1y                  TYPE DOUBLE PRECISION,
    ALTER COLUMN dividend_cagr_3y         TYPE DOUBLE PRECISION,
    ALTER COLUMN dma200_ratio             TYPE DOUBLE PRECISION,
    ALTER COLUMN dma50_ratio              TYPE DOUBLE PRECISION,
    ALTER COLUMN drawdown_from_ath        TYPE DOUBLE PRECISION,
    ALTER COLUMN earnings_growth_1y       TYPE DOUBLE PRECISION,
    ALTER COLUMN earnings_growth_3y_cagr  TYPE DOUBLE PRECISION,
    ALTER COLUMN eps_growth_3y_cagr       TYPE DOUBLE PRECISION,
    ALTER COLUMN eps_growth_yoy_q         TYPE DOUBLE PRECISION,
    ALTER COLUMN fcf_yield                TYPE DOUBLE PRECISION,
    ALTER COLUMN momentum_12m             TYPE DOUBLE PRECISION,
    ALTER COLUMN momentum_3m              TYPE DOUBLE PRECISION,
    ALTER COLUMN momentum_6m              TYPE DOUBLE PRECISION,
    ALTER COLUMN net_income_growth_yoy_q  TYPE DOUBLE PRECISION,
    ALTER COLUMN payout_ratio             TYPE DOUBLE PRECISION,
    ALTER COLUMN percent_insiders         TYPE DOUBLE PRECISION,
    ALTER COLUMN percent_institutions     TYPE DOUBLE PRECISION,
    ALTER COLUMN relative_volume          TYPE DOUBLE PRECISION,
    ALTER COLUMN return_1m                TYPE DOUBLE PRECISION,
    ALTER COLUMN return_1w                TYPE DOUBLE PRECISION,
    ALTER COLUMN return_1y                TYPE DOUBLE PRECISION,
    ALTER COLUMN return_3m                TYPE DOUBLE PRECISION,
    ALTER COLUMN return_3y                TYPE DOUBLE PRECISION,
    ALTER COLUMN return_6m                TYPE DOUBLE PRECISION,
    ALTER COLUMN return_ytd               TYPE DOUBLE PRECISION,
    ALTER COLUMN revenue_cagr_5y          TYPE DOUBLE PRECISION,
    ALTER COLUMN revenue_growth_1y        TYPE DOUBLE PRECISION,
    ALTER COLUMN revenue_growth_3y_cagr   TYPE DOUBLE PRECISION,
    ALTER COLUMN revenue_growth_yoy_q     TYPE DOUBLE PRECISION,
    ALTER COLUMN rsi_14                   TYPE DOUBLE PRECISION,
    ALTER COLUMN sharpe_1y                TYPE DOUBLE PRECISION,
    ALTER COLUMN short_interest_chg_1w    TYPE DOUBLE PRECISION,
    ALTER COLUMN short_pct                TYPE DOUBLE PRECISION,
    ALTER COLUMN volatility_20d           TYPE DOUBLE PRECISION,
    ALTER COLUMN volatility_60d           TYPE DOUBLE PRECISION;

CREATE VIEW screener.fundamentals AS
 SELECT asx_code,
        company_name,
        sector,
        industry,
        stock_type,
        status,
        market_cap,
        pe_ratio,
        forward_pe,
        peg_ratio,
        price_to_book,
        price_to_sales,
        price_to_cash_flow,
        price_to_fcf,
        ev,
        ev_to_ebitda,
        ev_to_ebit,
        ev_to_revenue,
        graham_number,
        dps_ttm,
        dividend_yield,
        franking_pct,
        grossed_up_yield,
        payout_ratio,
        dividend_cagr_3y,
        dividend_consecutive_yrs,
        revenue_ttm,
        gross_profit_ttm,
        ebitda_ttm,
        net_profit_ttm,
        gross_margin,
        ebitda_margin,
        net_margin,
        operating_margin,
        roe,
        roa,
        roce,
        avg_roe_3y,
        revenue_fy0,
        revenue_fy1,
        revenue_fy2,
        ebitda_fy0,
        ebitda_fy1,
        net_profit_fy0,
        net_profit_fy1,
        eps_fy0,
        eps_fy1,
        dps_fy0,
        dps_fy1,
        total_assets,
        total_equity,
        total_debt,
        net_debt,
        cash,
        book_value_per_share,
        debt_to_equity,
        current_ratio,
        cfo_fy0,
        capex_fy0,
        fcf_fy0,
        fcf_yield,
        revenue_growth_1y,
        revenue_growth_3y_cagr,
        revenue_cagr_5y,
        earnings_growth_1y,
        earnings_growth_3y_cagr,
        eps_growth_3y_cagr,
        revenue_growth_yoy_q,
        eps_growth_yoy_q,
        net_income_growth_yoy_q,
        revenue_growth_hoh,
        net_income_growth_hoh,
        eps_growth_hoh,
        piotroski_f_score,
        altman_z_score,
        return_1y,
        return_3y,
        return_5y,
        return_7y,
        return_10y,
        return_15y,
        analyst_rating,
        analyst_target_price,
        analyst_upside,
        shares_outstanding,
        percent_insiders,
        percent_institutions
   FROM screener.universe;

CREATE VIEW screener.technicals AS
 SELECT asx_code,
        company_name,
        sector,
        market_cap,
        price,
        price_date,
        open,
        high_52w,
        low_52w,
        volume,
        avg_volume_20d,
        rsi_14,
        macd,
        macd_signal,
        sma_20,
        sma_50,
        sma_200,
        ema_20,
        bb_upper,
        bb_lower,
        atr_14,
        adx_14,
        obv,
        return_1w,
        return_1m,
        return_3m,
        return_6m,
        return_1y,
        return_ytd,
        return_3y,
        return_5y,
        return_10y,
        momentum_3m,
        momentum_6m,
        momentum_12m,
        volatility_20d,
        volatility_60d,
        sharpe_1y,
        drawdown_from_ath,
        beta_1y,
        short_pct
   FROM screener.universe;

COMMIT;
