import type { Metadata } from 'next'
import { Brain, AlertTriangle, CheckCircle2, XCircle } from 'lucide-react'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'AI Insights Limitations | ASX Screener',
  description: 'Important limitations of AI-generated insights on ASX Screener. Understand what AI Insights can and cannot do before relying on them for research.',
  alternates: { canonical: 'https://asxscreener.com.au/ai-insights-limitations' },
}

export default function AIInsightsLimitationsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-10 space-y-8">
      <div>
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-purple-50 flex items-center justify-center shrink-0">
            <Brain className="w-5 h-5 text-purple-600" />
          </div>
          <h1 className="text-2xl font-bold text-slate-900">AI Insights — Limitations</h1>
        </div>
        <p className="text-sm text-slate-500">Last updated: June 2026</p>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6">
        <p className="font-semibold text-amber-900 mb-2 flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 shrink-0" /> Not financial advice
        </p>
        <p className="text-sm text-amber-800 leading-relaxed">
          AI Insights are an experimental research aid. They are generated by a large language model and <strong>must not be relied upon as financial advice, investment recommendations, or accurate statements of fact</strong>. Always verify AI responses from primary sources before acting on them.
        </p>
      </div>

      <div className="space-y-6 text-slate-700 leading-relaxed">

        <section>
          <h2 className="text-lg font-bold text-slate-900 mb-3">What AI Insights can help with</h2>
          <ul className="space-y-2">
            {[
              'Summarising publicly available information about a company in plain English',
              'Explaining what a financial metric means and how it is calculated',
              'Describing a company\'s reported business model, revenue streams, and sector',
              'Generating a starting framework for your own further research',
              'Explaining ASX-specific concepts like franking credits, JORC resources, or WALE',
            ].map(item => (
              <li key={item} className="flex items-start gap-2 text-sm">
                <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-slate-900 mb-3">What AI Insights cannot do</h2>
          <ul className="space-y-2">
            {[
              'Provide financial advice or investment recommendations',
              'Predict future share prices, earnings, or dividends',
              'Guarantee the accuracy of any data or company information',
              'Access real-time news, ASX announcements, or live prices',
              'Replace the analysis of a qualified financial adviser',
              'Account for your personal financial situation, tax position, or risk tolerance',
            ].map(item => (
              <li key={item} className="flex items-start gap-2 text-sm">
                <XCircle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-slate-900 mb-3">Known limitations</h2>
          <div className="space-y-4">
            {[
              {
                title: 'Knowledge cutoff',
                body: 'The underlying AI model has a training data cutoff date. Events, announcements, earnings results, and market developments after that date are not reflected in AI responses. Always check current ASX announcements for recent developments.',
              },
              {
                title: 'Hallucinations',
                body: 'Large language models can generate plausible-sounding but factually incorrect information — a phenomenon known as "hallucination". AI Insights may contain errors about company facts, financial figures, or market history. Treat all AI-generated statements as unverified until confirmed from primary sources.',
              },
              {
                title: 'No real-time data access',
                body: 'AI Insights do not have access to live prices, intraday trading data, or breaking news. Responses are based on the model\'s training data and any structured company data passed to it — not a live market feed.',
              },
              {
                title: 'Sector and company coverage gaps',
                body: 'AI coverage of smaller ASX companies (micro-cap and nano-cap) may be limited or inaccurate. Well-known large-cap companies generally have better AI coverage than small explorers or recently listed entities.',
              },
              {
                title: 'No tax advice',
                body: 'AI Insights cannot provide tax advice. Discussion of franking credits, CGT, or super contributions is for educational explanation only — not a substitute for advice from a registered tax agent.',
              },
            ].map(({ title, body }) => (
              <div key={title} className="bg-white border border-slate-200 rounded-xl p-4">
                <h3 className="font-semibold text-slate-800 mb-1.5">{title}</h3>
                <p className="text-sm text-slate-600 leading-relaxed">{body}</p>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold text-slate-900 mb-3">How to use AI Insights responsibly</h2>
          <ol className="space-y-3">
            {[
              'Use AI responses as a starting point for research, not a conclusion.',
              'Verify any specific claim (financial figures, dates, names) from the company\'s actual ASX filings.',
              'Do not make buy, sell, or hold decisions based solely on AI output.',
              'If an AI response seems wrong or surprising, it probably is — check the source.',
              'Consult a licensed financial adviser for advice specific to your situation.',
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-3 text-sm">
                <span className="w-5 h-5 rounded-full bg-purple-100 text-purple-700 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">{i + 1}</span>
                {item}
              </li>
            ))}
          </ol>
        </section>

      </div>

      <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 space-y-2">
        <h2 className="font-semibold text-slate-800 text-sm">Related pages</h2>
        <div className="flex flex-wrap gap-4">
          {[
            { href: '/disclaimer', label: 'Disclaimer' },
            { href: '/data-freshness', label: 'Data Freshness' },
            { href: '/terms', label: 'Terms of Service' },
            { href: '/learn/how-to-research-asx-stocks-dyor', label: 'DYOR Research Workflow' },
          ].map(({ href, label }) => (
            <Link key={href} href={href} className="text-sm text-blue-600 hover:underline">
              {label}
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}
