"""
What the run intended equals what the database contains — for every row
=======================================================================
The publication prerequisite, stated as one sentence:

    for every canonical row in the intended serving population, the canonical
    payload generated by this run equals the canonical payload read back from
    PostgreSQL.

Not a sample. The previous check read 25 codes, which is 1.2% of the serving
population, and 1.2% is a spot check whatever it is called. It could not
answer the question publication actually depends on: did the write land, in
full, for everyone.

Four things it proves, and they fail differently:

    population    the codes this run intended, the codes it wrote, and the
                  codes attributable to it in the table are the same set.
    attribution   every row carries THIS run id. A row belonging to another
                  run cannot verify this one, however correct it looks.
    contract      every governed metric is represented; a suppressed metric
                  is NULL with a state; an applicable one carries no
                  contradictory state; an unsupported computation carries its
                  cause.
    equality      the normalised intent payload and the normalised read-back
                  payload hash identically, per row.

The last one is what makes stale prior-run survival impossible to hide. A
value the run omitted and that simply persisted from run N-1 is
indistinguishable, in the final row, from one this run wrote — unless you
compare the final row against what this run meant to write. Population
equality plus per-row payload equality closes that without needing a
pre-state fingerprint: a surviving N-1 value is a payload difference.

Why the quantisation matters more than it looks
-----------------------------------------------
storage_value() does not round. Intent values are full-precision Python
floats; PostgreSQL rounds them to each column's declared scale on INSERT. So
0.123456789 is intended and 0.1235 is stored, and a naive comparison of the
two reports every row as a mismatch — a validator that blocks publication
permanently and for a reason that is not a defect.

The scales are therefore read from information_schema, not assumed. Not a
constant, not a guess at 6 decimal places: the database is asked what it will
do to the number, and the intent is put through the same transformation before
comparison. Anything else is a second definition of the storage contract, and
this codebase has been bitten five times in three days by exactly that.

Failures name the row and the metric and both values. A hash-only validator
that says "hashes differ" sends you back for another 25-minute run to learn
what it already knew — which is the mistake the previous version made by
counting violations and then rolling back the rows that explained them.
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from typing import Mapping, Optional, Sequence

log = logging.getLogger(__name__)

#: How many individual mismatches to name before summarising. Enough to see
#: the shape of a systematic failure; not so many that the log becomes the
#: thing you have to debug.
DETAIL_LIMIT = 40


@dataclass
class ReadBackReport:
    """Everything the caller needs to refuse, and to explain the refusal."""

    intended: int = 0
    written: int = 0
    read_back: int = 0
    missing: list[str] = field(default_factory=list)      # intended, not in DB
    unexpected: list[str] = field(default_factory=list)   # in DB, not intended
    mismatched: list[tuple[str, str, object, object]] = field(default_factory=list)
    contract: list[tuple[str, object]] = field(default_factory=list)
    hash_differs: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not (self.missing or self.unexpected or self.mismatched
                    or self.contract or self.hash_differs)

    @property
    def failure_count(self) -> int:
        return (len(self.missing) + len(self.unexpected) + len(self.mismatched)
                + len(self.contract) + len(self.hash_differs))

    def summary(self) -> str:
        if self.ok:
            return (f"read-back verified: {self.read_back:,} of "
                    f"{self.intended:,} rows, payload-identical")
        parts = []
        if self.missing:
            parts.append(f"{len(self.missing):,} intended rows absent")
        if self.unexpected:
            parts.append(f"{len(self.unexpected):,} unattributed rows")
        if self.mismatched:
            parts.append(f"{len(self.mismatched):,} field mismatches")
        if self.hash_differs:
            parts.append(f"{len(self.hash_differs):,} payload hash differences")
        if self.contract:
            parts.append(f"{len(self.contract):,} contract violations")
        return "read-back FAILED: " + "; ".join(parts)

    def log_detail(self) -> None:
        """Name the failures. A refusal that cannot be diagnosed costs a run."""
        log.error("%s", self.summary())
        for code in self.missing[:DETAIL_LIMIT]:
            log.error("  MISSING     %s — intended but not attributable to this run", code)
        for code in self.unexpected[:DETAIL_LIMIT]:
            log.error("  UNEXPECTED  %s — attributed to this run but never intended", code)
        for code, metric, want, got in self.mismatched[:DETAIL_LIMIT]:
            log.error("  MISMATCH    %-6s %-28s intended=%r stored=%r",
                      code, metric, want, got)
        for code, v in self.contract[:DETAIL_LIMIT]:
            log.error("  CONTRACT    %-6s %-28s %s", code,
                      getattr(v, "metric", "?"), v)
        for code in self.hash_differs[:DETAIL_LIMIT]:
            log.error("  PAYLOAD     %s — normalised payloads differ", code)
        if self.failure_count > DETAIL_LIMIT:
            log.error("  ... %s further failures not listed",
                      self.failure_count - DETAIL_LIMIT)


def column_scales(cur, columns: Sequence[str]) -> dict[str, Optional[int]]:
    """Each column's declared numeric scale, asked of the database.

    NULL for anything that is not NUMERIC — booleans and smallints have no
    scale and must not be quantised.

    Asked rather than assumed on purpose. The columns here span NUMERIC(10,6),
    NUMERIC(12,4), NUMERIC(8,4), SMALLINT and BOOLEAN; a single rounding
    constant would be right for some and silently wrong for the rest, and
    "silently wrong for the rest" is the failure this whole module exists to
    make impossible.
    """
    cur.execute("""
        SELECT column_name, numeric_scale
          FROM information_schema.columns
         WHERE table_schema = 'screener' AND table_name = 'universe'
           AND column_name = ANY(%s)
    """, (list(columns),))
    found = {name: scale for name, scale in cur.fetchall()}
    missing = [c for c in columns if c not in found]
    if missing:
        raise RuntimeError(
            f"screener.universe is missing columns the contract requires: "
            f"{missing}. The schema and the model disagree, and a read-back "
            f"cannot be meaningful across that.")
    return found


def quantise(value, scale: Optional[int]):
    """Put an intended value through what the column will do to it.

    Returns a string for numerics: Decimal comparison is exact, and a string
    hashes deterministically where a float's repr does not. Booleans and
    non-numerics pass through unchanged.
    """
    if value is None:
        return None
    if isinstance(value, bool) or scale is None:
        return value
    try:
        # ROUND_HALF_UP, not Python's default.
        #
        # Decimal.quantize() defaults to ROUND_HALF_EVEN (banker's rounding);
        # PostgreSQL NUMERIC rounds half AWAY FROM ZERO. They agree everywhere
        # except exact ties, and on ties they disagree whenever the preceding
        # digit is even — so 0.1234565 at scale 6 is 0.123456 in Python and
        # 0.123457 in PostgreSQL.
        #
        # That difference is invisible to any test with a fake cursor, and in
        # production it would surface as payload mismatches on whichever rows
        # happened to land on a boundary: a validator blocking publication for
        # its own rounding rather than for a defect, discovered at 25 minutes
        # a cycle. scripts/p0a_quantise_probe.py asks the database which mode
        # it uses rather than trusting this comment.
        return str(Decimal(str(value)).quantize(
            Decimal(1).scaleb(-scale), rounding=ROUND_HALF_UP))
    except (InvalidOperation, ValueError):
        # A value the column could not hold is a defect worth surfacing as a
        # mismatch rather than an exception: the comparison below will name
        # the metric, which an exception here would not.
        return f"UNQUANTISABLE:{value!r}"


def row_payload(assessments: Mapping[str, object],
                metrics: Sequence[str],
                scales: Mapping[str, Optional[int]],
                column_of) -> dict:
    """The normalised canonical contract for one row.

    Identical shape from either side — intent or read-back — because both are
    ``metric -> Assessment``. One renderer, so a difference between the sides
    cannot be an artefact of rendering them differently.
    """
    out: dict[str, object] = {}
    for metric in metrics:
        a = assessments.get(metric)
        if a is None:
            out[metric] = {"__absent__": True}
            continue
        out[metric] = {
            "v": quantise(a.value, scales.get(column_of(metric))),
            "s": a.state.value,
            "c": a.cause.value if getattr(a, "cause", None) is not None else None,
        }
    return out


def payload_hash(payload: Mapping[str, object]) -> str:
    """A deterministic fingerprint of one row's canonical contract."""
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":"),
                   default=str).encode("utf-8")
    ).hexdigest()


def verify_population(cur, by_code: Mapping[str, Mapping[str, object]],
                      run, rows_written: int) -> ReadBackReport:
    """Compare every intended row against every persisted row. No sampling.

    One bulk SELECT rather than a query per code: 2,103 round trips inside the
    publication transaction is not a validation strategy, it is a reason to
    keep sampling.
    """
    from compute.engine.metric_states import decode_all, load_states, violations
    from compute.engine.universe_writer import (
        column_for, governed_for, normalise,
    )

    metrics = sorted(governed_for(run.factor_model_version))
    columns = [column_for(m) for m in metrics]
    scales = column_scales(cur, columns)

    def column_of(metric: str) -> str:
        return column_for(normalise(metric))

    report = ReadBackReport(intended=len(by_code), written=rows_written)

    # Scoped to this run. A row written by anything else cannot satisfy the
    # check by accident, and a row this run failed to write cannot be covered
    # by one that already happened to be correct.
    cur.execute(
        f"SELECT asx_code, {', '.join(columns)}, metric_states "
        f"FROM screener.universe WHERE compute_run_id = %s",
        (run.run_id,))

    seen: set[str] = set()
    for row in cur.fetchall():
        code, values, states = row[0], row[1:-1], row[-1]
        seen.add(code)
        report.read_back += 1

        intent = by_code.get(code)
        if intent is None:
            report.unexpected.append(code)
            continue

        restored = decode_all(dict(zip(metrics, values)), load_states(states))

        # Field level first, so a failure names the metric and both values.
        # The hash is the attestation; it is not the diagnosis.
        want = row_payload(intent, metrics, scales, column_of)
        got = row_payload(restored, metrics, scales, column_of)
        for metric in metrics:
            if want[metric] != got[metric]:
                report.mismatched.append(
                    (code, metric, want[metric], got[metric]))

        if payload_hash(want) != payload_hash(got):
            report.hash_differs.append(code)

        # The contract, against what is actually stored.
        restored_values = {m: a.value for m, a in restored.items()}
        report.contract.extend(
            (code, v) for v in violations(restored_values, encode_states(restored),
                                          run.factor_model_version))

    report.missing = sorted(set(by_code) - seen)
    return report


def encode_states(assessments: Mapping[str, object]) -> dict:
    """The sidecar payload for a set of assessments.

    Wrapped rather than imported at module scope because metric_states imports
    from the applicability contract, and this module is also used by tooling
    that has no reason to load it until it needs it.
    """
    from compute.engine.metric_states import encode
    return encode(assessments)
